[project]
name = "oss-refusal-evaluation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.4.1",
    "matplotlib>=3.10.8",
    "pyyaml>=6.0.3",
    "vllm>=0.12.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.0",
]
