dataset_splits:
  - dataset_id: "JailbreakBench/JBB-Behaviors"
    config: "behaviors"
    prompt_column: "Goal"
  - dataset_id: "Iker/refusal-evaluation"
    split: "general_prompts"


model:
  name_or_path: "../../../../models/huggingface/Qwen/Qwen3-8B-FP8"
  max_model_len: 16384
  max_new_tokens: 8192
  thinking-string: "<think>"
  num_return_sequences: 5
  temperature: 0.6
  top_p: 0.95
  top_k: 20
  batch_size: 512

judge_model:
  name_or_path: "../../../../models/huggingface/unsloth/gpt-oss-20b"
  max_model_len: 16384
  max_new_tokens: 8192
  num_return_sequences: 1
  temperature: 0.6
  top_p: 0.95
  top_k: 20
  batch_size: 64


continue_from_checkpoint: true
gpu_memory_utilization: 0.95
tensor_parallel_size: "auto" # use all available GPUs

output_dir: "results/Qwen3-8B-FP8"
